"""update table name to add prefix tb_ for user and post

Revision ID: 2aba1a4d7b68
Revises: f315f7c11c45
Create Date: 2021-09-01 21:28:17.966716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2aba1a4d7b68'
down_revision = 'f315f7c11c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('u_id', sa.String(length=50), nullable=False),
    sa.Column('u_username', sa.String(length=50), nullable=False),
    sa.Column('u_password', sa.String(length=255), nullable=False),
    sa.Column('u_email', sa.String(length=255), nullable=False),
    sa.Column('u_fullname', sa.String(length=255), nullable=False),
    sa.Column('u_occupation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_username')
    )
    op.create_table('tb_post',
    sa.Column('p_id', sa.String(length=50), nullable=False),
    sa.Column('p_title', sa.String(length=50), nullable=False),
    sa.Column('p_subtitle', sa.String(length=255), nullable=True),
    sa.Column('p_content', sa.Text(), nullable=False),
    sa.Column('p_cover', sa.Text(), nullable=True),
    sa.Column('p_creator', sa.String(length=50), nullable=False),
    sa.Column('p_status', sa.String(length=4), nullable=False),
    sa.Column('p_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('p_updated_at', sa.DateTime(), nullable=True),
    sa.Column('p_published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['p_creator'], ['tb_user.u_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('p_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('p_title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('p_subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('p_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('p_cover', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('p_creator', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('p_status', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('p_created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('p_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('p_published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['p_creator'], ['user.u_id'], name='post_p_creator_fkey'),
    sa.PrimaryKeyConstraint('p_id', name='post_pkey')
    )
    op.create_table('user',
    sa.Column('u_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('u_username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('u_password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('u_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('u_fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('u_occupation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('u_id', name='user_pkey'),
    sa.UniqueConstraint('u_email', name='user_u_email_key'),
    sa.UniqueConstraint('u_username', name='user_u_username_key')
    )
    op.drop_table('tb_post')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
