"""update table id from interger to string(50)

Revision ID: f315f7c11c45
Revises: 14bd3fe2154e
Create Date: 2021-09-01 20:27:43.599577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f315f7c11c45'
down_revision = '14bd3fe2154e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('u_id', sa.String(length=50), nullable=False),
    sa.Column('u_username', sa.String(length=50), nullable=False),
    sa.Column('u_password', sa.String(length=80), nullable=False),
    sa.Column('u_email', sa.String(length=255), nullable=False),
    sa.Column('u_fullname', sa.String(length=255), nullable=False),
    sa.Column('u_occupation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_username')
    )
    op.create_table('post',
    sa.Column('p_id', sa.String(length=50), nullable=False),
    sa.Column('p_title', sa.String(length=50), nullable=False),
    sa.Column('p_subtitle', sa.String(length=255), nullable=True),
    sa.Column('p_content', sa.Text(), nullable=False),
    sa.Column('p_cover', sa.Text(), nullable=True),
    sa.Column('p_creator', sa.String(length=50), nullable=False),
    sa.Column('p_status', sa.String(length=4), nullable=False),
    sa.Column('p_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('p_updated_at', sa.DateTime(), nullable=True),
    sa.Column('p_published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['p_creator'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.drop_table('Post')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Post_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cover_picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['User.id'], name='Post_creator_fkey'),
    sa.PrimaryKeyConstraint('id', name='Post_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key'),
    sa.UniqueConstraint('user_id', name='User_user_id_key'),
    sa.UniqueConstraint('username', name='User_username_key')
    )
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
